{"name": "Создание заказа неавторизованным пользователем. Баг бэка: не возвращает ошибку", "status": "failed", "statusDetails": {"message": "AssertionError: assert (200 == 401)\n +  where 200 = <Response [200]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x000001FE42B48860>\n\n    @allure.title('Создание заказа неавторизованным пользователем. Баг бэка: не возвращает ошибку')\n    def test_create_order_by_not_auth_user(self):\n        data = OrderGenerate.generate_orger_list()\n        order = requests.post(URLS.ORDER_URL, data=data)\n>       assert order.status_code == 401 and order.json()['message'] == \"You should be authorised\"\nE       assert (200 == 401)\nE        +  where 200 = <Response [200]>.status_code\n\ntests\\test_create_order.py:21: AssertionError"}, "steps": [{"name": "Геренация списка ингредиентов для заказа", "status": "passed", "steps": [{"name": "Получение ингредиентов", "status": "passed", "start": 1719670032085, "stop": 1719670032175}], "start": 1719670032085, "stop": 1719670032175}], "start": 1719670032085, "stop": 1719670032261, "uuid": "332a277b-66b3-4ec6-85d8-df35e2672549", "historyId": "bbda267f6b3ce071f27b2ab5fcccbfb1", "testCaseId": "bbda267f6b3ce071f27b2ab5fcccbfb1", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_by_not_auth_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "msknbfb5654inb"}, {"name": "thread", "value": "11288-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}